#! /bin/sh
raku -MPod::To::Markdown ./lib/Template/Mustache.pm \
    | raku -pe '

my $gh-repo = "softmoth/p6-Template-Mustache";

say qq:to/END/ if $++ == 2;
[![Build Status](https://travis-ci.org/$gh-repo.svg?branch=master)](https://travis-ci.org/$gh-repo)
[![Windows status](https://ci.appveyor.com/api/projects/status/github/$gh-repo?branch=master&passingText=Windows%20-%20OK&failingText=Windows%20-%20FAIL&pendingText=Windows%20-%20pending&svg=true)](https://ci.appveyor.com/project/$gh-repo/branch/master)
END

' \
    > README.md
